### ISSUE TITLE
RFE: drop python<=3.7 support

### ISSUE THREAD

**Issue by kloczek** [bbangert/beaker#239]
Python 2.x has been EOSed more than 4 years ago and python 3.7 Jun last year.
https://endoflife.date/python

IMO it would be good to create 1.x branch and commit on that branch only critical fixes and start working on remove first all python 2.x support and than clean the code do drop python<=3.7.
First new stable release can be like 2.0.0.
`pyupgrade --py38-plus` command generated +28KB patch on top of which is possible to make probably another ~20KBmanual changes.

PS. Sep this year will be EOSed python 3.8 but if all code up to then will be cleaned remove python 3.8 support can be almost instantly generated using `pyupgrade --py39-plus` commend.

**Comment by kloczek** [comment]
This RFE i snot about abandon support of any of those python versions. 😄 
It is about branch current tree and backport only critical changes to be able keep on master 100% c;lean code supporting only not EOSed python versions 😋 
Benefit of that is that should allow remove and/or clen a lot of code which would fully compensate devel man/hours spend on backporting critical changes.
Only this and nothing more ..

**Comment by amol-** [comment]
I'm not convinced that it would compensate the labour necessary to maintain two branches, practically rewriting everything twice, especially as the codebase starts to diverge and thus changes might not easily merge anymore. Plus the initial effort at upgrading the codebase (and no, `pyupgrade --py39-plus` is not enough if you want to actually take benefit on the new patterns that are available in newer versions instead of just changing `set(...)` to `{...}` which is little more than syntactic sugar)

**Comment by amol-** [comment]
> Please .. I'm not talking about create two branches. I'm talking about one branch and backport only **critical fixes**.
> 

I have no interest in backporting only critical fixes given that the Beaker users of versions < 3.9 are still the majority, so it would imply maintaining two branches. I still don't see the benefit of this and I will personally phase out Python versions when I see them going in disuse between our users.
